[package]
name = "cavy-core"
version = "0.1.0"
authors = ["mcncm <cavy-lang-support@mit.edu>"]
edition = "2018"
build = "build.rs"

[dependencies]
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.0"
dirs = "2.0.2"
cavy-macros = { path = "../cavy-macros" }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
