[package]
authors = ["mcncm <cavy-lang-support@mit.edu>"]
build = "build.rs"
edition = "2018"
name = "cavy-core"
version = "0.1.0"
[dependencies]
dirs = "2.0.2"
disjoint-sets = "*"
serde_json = "1.0"

[dependencies.cavy-macros]
path = "../cavy-macros"

[dependencies.serde]
features = ["derive"]
version = "1.0.113"

[dev-dependencies]
[dev-dependencies.cargo-husky]
default-features = false
features = ["user-hooks"]
version = "1"
