[workspace]
members = [
    "hafnia",
    "hafnia-core",
    "hafnia-macros",
    "hafnia-cli",
    "hafnia-inline",
]
default-members = ["hafnia-cli"]

[profile.release]
lto = "fat"
codegen-units = 1
