[package]
name = "cavy-inline"
version = "0.1.0"
authors = ["mcncm <33966432+mcncm@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
cavy-core = { path = "../cavy-core" }
quote = "1.0"
syn = "1.0"

[features]
nightly-features = []
